<!-- html content body -->
<table border=1>
[+content+]
</table>
<!-- REMOVE:START content -->

<!-- SEARCH:title -->
<tr><td align="center" bgcolor="#EEEEEE">key</td><td align="center" bgcolor="#EEEEEE">value</td></tr>
<!-- SEARCH:content1 -->
<tr><th align="left" valign="top" bgcolor="#EEEEEE">[+key+]</th><td>[+value+]</td></tr>
<!-- SEARCH:content2 -->
<tr><td align="left">[+key+]</td><td>[+value+]</td></tr>
<!-- SEARCH:header1 -->
<tr><th align="left" colspan="2" bgcolor="#DDFEFE">[+key+]</th></tr>
<!-- SEARCH:END -->

<!-- SEARCH:apilink1 -->
<!-- apilink1 --><a href='[+baseurl+]/index/service/uid/[+userid+]/[+MODELS+]/[+apiname+]?[+params+]'>[+linktext+]</a>
<!-- SEARCH:apilink2 -->
<!-- apilink2 --><br><a href='[+baseurl+]/index/service/uid/[+userid+]/[+MODELS+]/[+apiname+]?[+params+]'>[+linktext+]</a>
<!-- SEARCH:END -->

<!-- REMOVE:END -->
