heat_template_version: 2013-05-23

description: >
  WLM(cfn) scenario test CFN-3-6A. test template for floatingIP

parameters:
  # floating ip and router
  public_net_id:
    type: string
    description: >
      ID of public network for which floating IP addresses will be allocated
    default: d2bef1c2-7059-4cd4-b7c7-4fa5180049be
    constraints:
      - allowed_values:
        - soken00-network-floatingip
        #pre
        - d2bef1c2-7059-4cd4-b7c7-4fa5180049be
        #  description: ext-net on PreStage
        #prepre
        - b98913fd-570e-4790-88ed-c441ed1432a6
        #  description: ext-net on PrePreStage
        - c046c789-8956-4beb-8cfa-669969fbca68
        #  description: ext-net2 (on PrePreStage)

resources:
  # floating ip
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }

outputs:
  floating_ip_info:
    description: test fip floatingIP
    value: { get_attr: [floating_ip, show] }
