heat_template_version: 2013-05-23

description: >
  WLM(cfn) scenario test CFN-3-6. CentOS or win2012 admin_pwd sshkey 1VM

parameters:
  key_name:
    description: The EC2 Key Pair to allow SSH access to the instances
    type: string

  AZ:
    description: FJ nextS5 availability_zone on Region
    type: string
    default: jp-east-1a
    constraints:
      - allowed_values:
        - jp-east-1a
        - jp-east-1b
        - nova

  instance_type:
    description: Server EC2 instance type
    type: string
    default: m1.small
    constraints:
      - allowed_values:
        - m1.small
        - m1.medium
        - m1.large

  instance_image:
    description: instance image
    type: string
    default: CentOS-6.6_20141127
    constraints:
      - allowed_values:
        - CentOS-6.6_20141127
        - CentOS-6.6-mini_20141106
        - centos-6.5-64bit-en-global-30g
        - Windows Server 2008 R2 SE 64bit SP1 (Japanese)
        - Windows Server 2008 R2 EE 64bit SP1 (Japanese)
        - Windows Server 2012 R2 SE 64bit (Japanese)
        - windows_server_2012_r2_standard_eval_kvm_20140607
        - w2k12r2se-64bit-jp-jp-80g-2014

  SSHLocation:
    description: The IP address range that can be used to SSH to the EC2 instances
    type: string
    default: 0.0.0.0/0
    constraints:
      - length: { min: 9, max: 18 }
        description: must be between 9 and 18 characters
      - allowed_pattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
        description: must be a valid IP CIDR range of the form x.x.x.x/x.

  admin_pass:
    type: string
    description: Admin password
    hidden: true
    constraints:
      - length: { min: 6, max: 8 }
        description: Password length must be between 6 and 8 characters
      - allowed_pattern: "[a-zA-Z0-9]+"
        description: Password must consist of characters and numbers only
      - allowed_pattern: "[A-Z]+[a-zA-Z0-9]*"
        description: Password must start with an uppercase character


  private_net_name:
    type: string
    description: Name of private network to be created
    default: soken00-network-private11
    constraints:
      - allowed_values:
        - soken00-network-private11
        - soken00-network-private12
        - soken00-network-private13
        - ext-net

  private_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 192.168.11.0/24
    constraints:
      - allowed_values:
        - 192.168.11.0/24
        - 192.168.12.0/24
        - 192.168.13.0/24


resources:
  #network
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_net_name }

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: { get_param: private_net_cidr }


  # server
  server_1:
    type: OS::Nova::Server
    properties:
      name: server_1
      image:  { get_param: instance_image }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      admin_pass: { get_param: admin_pass }
      networks:
        - port: { get_resource: server1_port }

  server1_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }


outputs:
  server_1_show:
    description: server_1 information.
    value: { get_attr: [server_1, show] }

