heat_template_version: 2013-05-23

description: WLM cfn A Sample heat orchestration template for the PRE STAGING environment with ELB.

parameters:
  InstanceType:
    description: WebServer EC2 instance type
    type: string
    default: m1.small
    constraints:
      - allowed_values:
        - m1.tiny
        - m1.small
        - m1.medium
        - m1.large
        - economy
        - standard
        - advanced
        - high-performance

  Image:
    description: WebServer EC2 instance Image
    type: string
    default: CentOS-6.6_20141127
    constraints:
      - allowed_values:
        - CentOS-6.6_20141127
        - centos-6.5-64bit-en-global-30g-20140908-1.0-simple
        - CentOS-6.5-mini+

  private_net_name:
    type: string
    description: Name of private network to be created
    default: soken00-network-private14
    constraints:
      - allowed_values:
        - soken00-network-private11
        - soken00-network-private12
        - soken00-network-private13
        - soken00-network-private14
        - ext-net

  private_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 192.168.14.0/24
    constraints:
      - allowed_values:
        - 192.168.10.0/24
        - 192.168.11.0/24
        - 192.168.12.0/24
        - 192.168.13.0/24
        - 192.168.14.0/24

resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_net_name }

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: { get_param: private_net_cidr }

  # server 1
  server_1:
    type: OS::Nova::Server
    properties:
      image: { get_param: Image }
      flavor: { get_param: InstanceType }
      networks:
        - port: { get_resource: server1_port }

  server1_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }

  # server 2
  server_2:
    type: OS::Nova::Server
    properties:
      image: { get_param: Image }
      flavor: { get_param: InstanceType }
      networks:
        - port: { get_resource: server2_port }

  server2_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }

  #ELB
#
#AWS sample
#  elastic_load_balancer:
#    type: OS::Neutron::LoadBalancerFJ::ExpandableLoadBalancer::LoadBalancer
#    properties:
#      Subnets: [ get_resource: private_subnet ]
##      Instances: [ get_resource: server_1, get_resource: server_2 ]
#      Listeners:
#      - { LoadBalancerPort: '80', InstancePort: '80', Protocol: 'HTTP', InstanceProtocol: 'HTTP' }
#      HealthCheck: {Target: 'HTTP:80/', HealthyThreshold: '3', UnhealthyThreshold: '5', Interval: '30', Timeout: '5' }
#      Version: 2014-09-30
#      LoadBalancerName: load_balancer_name_web

#
#Openstack sample
  elastic_load_balancer:
    type: OS::Neutron::LoadBalancer
    properties:
      members: [ { get_resource: server_1 }, { get_resource: server_2 } ]
      pool_id: private_subnet
      protocol_port: 80



outputs:
  server_1_show:
    description: server_1 information.
    value: { get_attr: [server_1, show] }

  server_2_show:
    description: server_2 information.
    value: { get_attr: [server_2, show] }

